### PR TITLE
Add Homebrew install to readme

### PR DESCRIPTION
**Pull request by SeekingMeaning**
https://formulae.brew.sh/formula/chalk-cli

### CODE REVIEW

**Comment by Qix-** [comment]
Is this necessary? Node ships with `npm`, and Node would have to be a dependency anyway. Plus, it's not _as_ common that Node is managed via homebrew - usually people developing for Node are using `n` or `nvm` - at which point, `npm i -g chalk-cli` is the preferred (and only officially supported) installation method.

Where would it end? Would every Node.js binary be added to Homebrew? So then there would be two (three if you count `npx`) package managers serving all of these binaries? What about `PATH` conflicts?

I'm pretty :-1: on this. Let's leave Homebrew to the more fundamental binaries...

**Comment by SeekingMeaning** [comment]
I would argue that `chalk-cli` can useful outside the NPM ecosystem

**Comment by Qix-** [comment]
Most Node.js applications are useful outside of Node development et al. However, chalk still needs node.js to run, ultimately. And Node comes pre-packaged with npm anyway.

**Comment by SeekingMeaning** [comment]
For me, I like to install packages through Homebrew because then they're self-contained; my local NPM  instance does not need to be "polluted" with dependencies and such

**Comment by Qix-** [comment]
What difference does it make if your global package registry has chalk-cli or not? You're not importing from the global node_modules are you?

**Comment by sindresorhus** [comment]
I'm not interested in this. And I'm surprised it was even accepted. Homebrew's policy has always been to not vend packages already available in programming language package managers. Maybe they changed the policy at some point.

**Pull request closed without merging**
